Adjust atol/rtol to allow higher tolerance when comparing r2 results
Summary:
When comparing r2_score and scikit-learn's r2 scores, assertion errors raise due to floating point precision of outputs of torcheval and scikit-learn. Thus, we adjust atol/rtol to allow higher tolerance.

*Error message:*
```
FAIL: test_r2_score_base (torcheval.tests.metrics.functional.regression.test_r2_score.TestR2Score)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/torcheval/tests/metrics/functional/regression/__test_regression__/test_regression#link-tree/torcheval/tests/metrics/functional/regression/test_r2_score.py", line 51, in test_r2_score_base
    self._test_r2_score_with_input(input, target, "raw_values")
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/torcheval/tests/metrics/functional/regression/__test_regression__/test_regression#link-tree/torcheval/tests/metrics/functional/regression/test_r2_score.py", line 34, in _test_r2_score_with_input
    torch.testing.assert_close(
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/torcheval/tests/metrics/functional/regression/__test_regression__/test_regression#link-tree/torch/testing/_comparison.py", line 1342, in assert_close
    assert_equal(
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/torcheval/tests/metrics/functional/regression/__test_regression__/test_regression#link-tree/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Absolute difference: 3.888271749019623e-07 (up to 1e-08 allowed)
Relative difference: 5.8001848140325294e-05 (up to 1e-05 allowed)
```

Reviewed By: DuYicong515

Differential Revision: D37765687

fbshipit-source-id: 233e28b6472e578bb2fbe638e4c11e316cf5f065